repos:
  - repo: local
    hooks:
      - id: detect-legacy-paths
        name: Detect legacy paths
        entry: >-
          bash -c "git diff --cached --name-only |
          grep -Ei '(^|/)(legacy|shim)/|legacy|shim' |
          grep -v -E '^\.github/workflows/no-legacy.yml$|^tests/ci/test_no_legacy.py$|^tests/test_no_legacy_patterns.py$'
          && exit 1 || exit 0"
        language: system
        pass_filenames: false
      - id: detect-legacy-imports
        name: Detect legacy imports
        entry: bash -c "grep -R --line-number -E 'import (oldlib|jules\.legacy)' $(git diff --cached --name-only -- '*.py') && exit 1 || exit 0"
        language: system
        pass_filenames: false
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-no-eval
  - repo: https://github.com/trailofbits/pip-audit
    rev: v2.7.0
    hooks:
      - id: pip-audit
