version: '3.9'

services:
  jules:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8000:8000'
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/app:/app/app
      - ./data:/app/data
  # Chroma vector database, empty instance ready for use
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma
    ports:
      - "8001:8000"  # Chroma HTTP API
    volumes:
      - ./.chroma-data:/data  # persisted vector store
    restart: unless-stopped
