version: "3.9"

x-debug-logging: &debug-logging
  driver: json-file
  options:
    max-size: "50m"
    max-file: "5"

services:
  jules:
    environment:
      JULES_DEBUG: "1"
    # Override the base `command:` so we only run the debug entrypoint.
    command: []
    entrypoint:
      - python
      - -m
      - backend.cli
      - --debug
    logging: *debug-logging

    volumes:
      - ./backend:/app/backend
      - ./worker:/app/worker

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    # No additional CMD arguments – rely solely on the custom entrypoint.
    command: []
    volumes:
      - ./backend:/app/backend
      - ./backend/app:/app/app
      - ./worker:/app/worker
      - ./db:/app/db
      - ./jules:/app/jules
      - ./data:/app/data
      - ./worker:/app/worker
    environment:
      JULES_DEBUG: "1"
    entrypoint:
      - python
      - -m
      - worker.cli
      - --debug
    logging: *debug-logging

  chroma:
    environment:
      RUST_LOG: debug
    logging: *debug-logging
