version: '3.9'

services:
  jules:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      CHROMA_HOST: chroma
      CHROMA_TELEMETRY_ENABLED: 'false'
    ports:
      - '8000:8000'
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/app:/app/app
      - ./db:/app/db
      - ./jules:/app/jules
      - ./data:/app/data
  # Chroma vector database, empty instance ready for use
  chroma:
    image: ghcr.io/chroma-core/chroma:0.5.23
    environment:
      CHROMA_SERVER_TELEMETRY_ENABLED: 'false'
      CHROMA_SERVER_AUTH_PROVIDER: none
    volumes:
      # Persist Chroma data locally.  As of Chroma 0.5.x the server stores
      # its SQLite database + HNSW indexes inside /chroma/chroma/ (without the dot).
      # Keep the host files under data/chromadb/* for clarity rather than a
      # hidden dot-folder.
      - ./data/chromadb:/chroma/chroma
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8000"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 15s
