version: '3.9'

services:
  jules:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      CHROMA_HOST: chroma
    ports:
      - '8000:8000'
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/app:/app/app
      - ./db:/app/db
      - ./jules:/app/jules
      - ./data:/app/data
  # Chroma vector database, empty instance ready for use
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      # Persist Chroma data locally
      - ./.chroma-data:/chroma/.chroma
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8000/api/v1/heartbeat || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 15s
