[retrieval]
model = "gpt-3.5-turbo-0125"            # small & cheap – decision + summarisation
k = 8                                     # max Chroma hits
summary_tokens = 150                      # cheat-sheet length budget

[jules]
model = "gpt-4o-mini"                     # heavyweight reasoning model
temperature = 0.3
max_tokens = 1024

