name: Dependency audit
on: [pull_request]
permissions:
  contents: read
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install tools
        run: |
          pip install pip-audit pip-licenses
          pip install -r backend/requirements.txt
      - name: Security audit
        run: pip-audit --strict
      - name: License audit
        run: pip-licenses --fail-on=GPL,LGPL,AGPL
