name: Tests
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.8.2
      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-root
      - name: Validate lock file & pyproject
        run: poetry check
      - name: Ensure single LangChain package only
        run: |
          if poetry show --top-level | grep -qE "^langchain-(core|community)"; then
            echo "❌ Split langchain packages detected. Keep only monolith entry." >&2
            poetry show --top-level | grep -E "^langchain-(core|community|openai)" >&2 || true
            exit 1
          else
            echo "✅ Only monolith LangChain present"
          fi
      - name: Start services
        run: docker compose up -d chroma
      - name: Run tests
        env:
          JULES_DEBUG: "0"
        run: poetry run pytest -m "not slow"
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/*.jsonl
          if-no-files-found: ignore
